// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CartService.proto

package com.cd.proto;

public interface AddCartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddCartRequest)
    com.google.protobuf.MessageOrBuilder {
}
