// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CartService.proto

package com.cd.proto;

public interface AddToCartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddToCartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 cart_id = 1;</code>
   * @return The cartId.
   */
  int getCartId();

  /**
   * <code>int32 product_id = 2;</code>
   * @return The productId.
   */
  int getProductId();
}
