// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CartService.proto

package com.cd.proto;

public interface AddToCartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddToCartResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Response response = 1;</code>
   * @return Whether the response field is set.
   */
  boolean hasResponse();
  /**
   * <code>.Response response = 1;</code>
   * @return The response.
   */
  com.cd.proto.Response getResponse();
  /**
   * <code>.Response response = 1;</code>
   */
  com.cd.proto.ResponseOrBuilder getResponseOrBuilder();

  /**
   * <code>.Product product = 2;</code>
   * @return Whether the product field is set.
   */
  boolean hasProduct();
  /**
   * <code>.Product product = 2;</code>
   * @return The product.
   */
  com.cd.proto.Product getProduct();
  /**
   * <code>.Product product = 2;</code>
   */
  com.cd.proto.ProductOrBuilder getProductOrBuilder();
}
