// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CartService.proto

package com.cd.proto;

/**
 * Protobuf type {@code AddToCartRequest}
 */
public final class AddToCartRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AddToCartRequest)
    AddToCartRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddToCartRequest.newBuilder() to construct.
  private AddToCartRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddToCartRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AddToCartRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cd.proto.CartServiceOuterClass.internal_static_AddToCartRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cd.proto.CartServiceOuterClass.internal_static_AddToCartRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cd.proto.AddToCartRequest.class, com.cd.proto.AddToCartRequest.Builder.class);
  }

  public static final int CART_ID_FIELD_NUMBER = 1;
  private int cartId_ = 0;
  /**
   * <code>int32 cart_id = 1;</code>
   * @return The cartId.
   */
  @java.lang.Override
  public int getCartId() {
    return cartId_;
  }

  public static final int PRODUCT_ID_FIELD_NUMBER = 2;
  private int productId_ = 0;
  /**
   * <code>int32 product_id = 2;</code>
   * @return The productId.
   */
  @java.lang.Override
  public int getProductId() {
    return productId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cartId_ != 0) {
      output.writeInt32(1, cartId_);
    }
    if (productId_ != 0) {
      output.writeInt32(2, productId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (cartId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, cartId_);
    }
    if (productId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, productId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cd.proto.AddToCartRequest)) {
      return super.equals(obj);
    }
    com.cd.proto.AddToCartRequest other = (com.cd.proto.AddToCartRequest) obj;

    if (getCartId()
        != other.getCartId()) return false;
    if (getProductId()
        != other.getProductId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CART_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCartId();
    hash = (37 * hash) + PRODUCT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getProductId();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cd.proto.AddToCartRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cd.proto.AddToCartRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cd.proto.AddToCartRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cd.proto.AddToCartRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cd.proto.AddToCartRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cd.proto.AddToCartRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cd.proto.AddToCartRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cd.proto.AddToCartRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cd.proto.AddToCartRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cd.proto.AddToCartRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cd.proto.AddToCartRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cd.proto.AddToCartRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cd.proto.AddToCartRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AddToCartRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AddToCartRequest)
      com.cd.proto.AddToCartRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cd.proto.CartServiceOuterClass.internal_static_AddToCartRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cd.proto.CartServiceOuterClass.internal_static_AddToCartRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cd.proto.AddToCartRequest.class, com.cd.proto.AddToCartRequest.Builder.class);
    }

    // Construct using com.cd.proto.AddToCartRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      cartId_ = 0;
      productId_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cd.proto.CartServiceOuterClass.internal_static_AddToCartRequest_descriptor;
    }

    @java.lang.Override
    public com.cd.proto.AddToCartRequest getDefaultInstanceForType() {
      return com.cd.proto.AddToCartRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.cd.proto.AddToCartRequest build() {
      com.cd.proto.AddToCartRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cd.proto.AddToCartRequest buildPartial() {
      com.cd.proto.AddToCartRequest result = new com.cd.proto.AddToCartRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.cd.proto.AddToCartRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.cartId_ = cartId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.productId_ = productId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cd.proto.AddToCartRequest) {
        return mergeFrom((com.cd.proto.AddToCartRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cd.proto.AddToCartRequest other) {
      if (other == com.cd.proto.AddToCartRequest.getDefaultInstance()) return this;
      if (other.getCartId() != 0) {
        setCartId(other.getCartId());
      }
      if (other.getProductId() != 0) {
        setProductId(other.getProductId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              cartId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              productId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int cartId_ ;
    /**
     * <code>int32 cart_id = 1;</code>
     * @return The cartId.
     */
    @java.lang.Override
    public int getCartId() {
      return cartId_;
    }
    /**
     * <code>int32 cart_id = 1;</code>
     * @param value The cartId to set.
     * @return This builder for chaining.
     */
    public Builder setCartId(int value) {

      cartId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 cart_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCartId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      cartId_ = 0;
      onChanged();
      return this;
    }

    private int productId_ ;
    /**
     * <code>int32 product_id = 2;</code>
     * @return The productId.
     */
    @java.lang.Override
    public int getProductId() {
      return productId_;
    }
    /**
     * <code>int32 product_id = 2;</code>
     * @param value The productId to set.
     * @return This builder for chaining.
     */
    public Builder setProductId(int value) {

      productId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 product_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      productId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AddToCartRequest)
  }

  // @@protoc_insertion_point(class_scope:AddToCartRequest)
  private static final com.cd.proto.AddToCartRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cd.proto.AddToCartRequest();
  }

  public static com.cd.proto.AddToCartRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddToCartRequest>
      PARSER = new com.google.protobuf.AbstractParser<AddToCartRequest>() {
    @java.lang.Override
    public AddToCartRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AddToCartRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddToCartRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cd.proto.AddToCartRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

