// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CartService.proto

package com.cd.proto;

public final class CartServiceOuterClass {
  private CartServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddCartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddCartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddToCartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddToCartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteFromCartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteFromCartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddCartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddCartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddToCartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddToCartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteFromCartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteFromCartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ValidationError_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ValidationError_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Product_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021CartService.proto\"\020\n\016AddCartRequest\"!\n" +
      "\016GetCartRequest\022\017\n\007cart_id\030\001 \001(\005\"7\n\020AddT" +
      "oCartRequest\022\017\n\007cart_id\030\001 \001(\005\022\022\n\nproduct" +
      "_id\030\002 \001(\005\"A\n\025DeleteFromCartRequest\022\017\n\007ca" +
      "rt_id\030\001 \001(\005\022\027\n\017cart_product_id\030\002 \001(\005\"?\n\017" +
      "AddCartResponse\022\033\n\010response\030\001 \001(\0132\t.Resp" +
      "onse\022\017\n\007cart_id\030\002 \001(\005\"[\n\017GetCartResponse" +
      "\022\033\n\010response\030\001 \001(\0132\t.Response\022\017\n\007cart_id" +
      "\030\002 \001(\005\022\032\n\010products\030\003 \003(\0132\010.Product\"K\n\021Ad" +
      "dToCartResponse\022\033\n\010response\030\001 \001(\0132\t.Resp" +
      "onse\022\031\n\007product\030\002 \001(\0132\010.Product\"5\n\026Delet" +
      "eFromCartResponse\022\033\n\010response\030\001 \001(\0132\t.Re" +
      "sponse\"T\n\010Response\022\033\n\004code\030\001 \001(\0162\r.Respo" +
      "nseCode\022+\n\021validation_errors\030\002 \003(\0132\020.Val" +
      "idationError\"1\n\017ValidationError\022\r\n\005field" +
      "\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\"V\n\007Product\022\n\n\002id" +
      "\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\023\n\013description\030\003 \001(" +
      "\t\022\r\n\005price\030\004 \001(\001\022\r\n\005stock\030\005 \001(\005*A\n\014Respo" +
      "nseCode\022\006\n\002OK\020\000\022\017\n\013BAD_REQUEST\020\001\022\r\n\tNOT_" +
      "FOUND\020\002\022\t\n\005ERROR\020\0032\340\001\n\013CartService\022,\n\007ad" +
      "dCart\022\017.AddCartRequest\032\020.AddCartResponse" +
      "\022,\n\007getCart\022\017.GetCartRequest\032\020.GetCartRe" +
      "sponse\0222\n\taddToCart\022\021.AddToCartRequest\032\022" +
      ".AddToCartResponse\022A\n\016deleteFromCart\022\026.D" +
      "eleteFromCartRequest\032\027.DeleteFromCartRes" +
      "ponseB\020\n\014com.cd.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AddCartRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AddCartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddCartRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetCartRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetCartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCartRequest_descriptor,
        new java.lang.String[] { "CartId", });
    internal_static_AddToCartRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AddToCartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddToCartRequest_descriptor,
        new java.lang.String[] { "CartId", "ProductId", });
    internal_static_DeleteFromCartRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_DeleteFromCartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteFromCartRequest_descriptor,
        new java.lang.String[] { "CartId", "CartProductId", });
    internal_static_AddCartResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_AddCartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddCartResponse_descriptor,
        new java.lang.String[] { "Response", "CartId", });
    internal_static_GetCartResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetCartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCartResponse_descriptor,
        new java.lang.String[] { "Response", "CartId", "Products", });
    internal_static_AddToCartResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_AddToCartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddToCartResponse_descriptor,
        new java.lang.String[] { "Response", "Product", });
    internal_static_DeleteFromCartResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_DeleteFromCartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteFromCartResponse_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Code", "ValidationErrors", });
    internal_static_ValidationError_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_ValidationError_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ValidationError_descriptor,
        new java.lang.String[] { "Field", "Message", });
    internal_static_Product_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Product_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Price", "Stock", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
