// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CartService.proto

package com.cd.proto;

public interface DeleteFromCartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteFromCartResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Response response = 1;</code>
   * @return Whether the response field is set.
   */
  boolean hasResponse();
  /**
   * <code>.Response response = 1;</code>
   * @return The response.
   */
  com.cd.proto.Response getResponse();
  /**
   * <code>.Response response = 1;</code>
   */
  com.cd.proto.ResponseOrBuilder getResponseOrBuilder();
}
