// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CartService.proto

package com.cd.proto;

/**
 * Protobuf type {@code GetCartResponse}
 */
public final class GetCartResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetCartResponse)
    GetCartResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetCartResponse.newBuilder() to construct.
  private GetCartResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetCartResponse() {
    products_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetCartResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cd.proto.CartServiceOuterClass.internal_static_GetCartResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cd.proto.CartServiceOuterClass.internal_static_GetCartResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cd.proto.GetCartResponse.class, com.cd.proto.GetCartResponse.Builder.class);
  }

  public static final int RESPONSE_FIELD_NUMBER = 1;
  private com.cd.proto.Response response_;
  /**
   * <code>.Response response = 1;</code>
   * @return Whether the response field is set.
   */
  @java.lang.Override
  public boolean hasResponse() {
    return response_ != null;
  }
  /**
   * <code>.Response response = 1;</code>
   * @return The response.
   */
  @java.lang.Override
  public com.cd.proto.Response getResponse() {
    return response_ == null ? com.cd.proto.Response.getDefaultInstance() : response_;
  }
  /**
   * <code>.Response response = 1;</code>
   */
  @java.lang.Override
  public com.cd.proto.ResponseOrBuilder getResponseOrBuilder() {
    return response_ == null ? com.cd.proto.Response.getDefaultInstance() : response_;
  }

  public static final int CART_ID_FIELD_NUMBER = 2;
  private int cartId_ = 0;
  /**
   * <code>int32 cart_id = 2;</code>
   * @return The cartId.
   */
  @java.lang.Override
  public int getCartId() {
    return cartId_;
  }

  public static final int PRODUCTS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.cd.proto.Product> products_;
  /**
   * <code>repeated .Product products = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.cd.proto.Product> getProductsList() {
    return products_;
  }
  /**
   * <code>repeated .Product products = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.cd.proto.ProductOrBuilder> 
      getProductsOrBuilderList() {
    return products_;
  }
  /**
   * <code>repeated .Product products = 3;</code>
   */
  @java.lang.Override
  public int getProductsCount() {
    return products_.size();
  }
  /**
   * <code>repeated .Product products = 3;</code>
   */
  @java.lang.Override
  public com.cd.proto.Product getProducts(int index) {
    return products_.get(index);
  }
  /**
   * <code>repeated .Product products = 3;</code>
   */
  @java.lang.Override
  public com.cd.proto.ProductOrBuilder getProductsOrBuilder(
      int index) {
    return products_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (response_ != null) {
      output.writeMessage(1, getResponse());
    }
    if (cartId_ != 0) {
      output.writeInt32(2, cartId_);
    }
    for (int i = 0; i < products_.size(); i++) {
      output.writeMessage(3, products_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (response_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getResponse());
    }
    if (cartId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, cartId_);
    }
    for (int i = 0; i < products_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, products_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cd.proto.GetCartResponse)) {
      return super.equals(obj);
    }
    com.cd.proto.GetCartResponse other = (com.cd.proto.GetCartResponse) obj;

    if (hasResponse() != other.hasResponse()) return false;
    if (hasResponse()) {
      if (!getResponse()
          .equals(other.getResponse())) return false;
    }
    if (getCartId()
        != other.getCartId()) return false;
    if (!getProductsList()
        .equals(other.getProductsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasResponse()) {
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getResponse().hashCode();
    }
    hash = (37 * hash) + CART_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCartId();
    if (getProductsCount() > 0) {
      hash = (37 * hash) + PRODUCTS_FIELD_NUMBER;
      hash = (53 * hash) + getProductsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cd.proto.GetCartResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cd.proto.GetCartResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cd.proto.GetCartResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cd.proto.GetCartResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cd.proto.GetCartResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cd.proto.GetCartResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cd.proto.GetCartResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cd.proto.GetCartResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cd.proto.GetCartResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cd.proto.GetCartResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cd.proto.GetCartResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cd.proto.GetCartResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cd.proto.GetCartResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetCartResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetCartResponse)
      com.cd.proto.GetCartResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cd.proto.CartServiceOuterClass.internal_static_GetCartResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cd.proto.CartServiceOuterClass.internal_static_GetCartResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cd.proto.GetCartResponse.class, com.cd.proto.GetCartResponse.Builder.class);
    }

    // Construct using com.cd.proto.GetCartResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      response_ = null;
      if (responseBuilder_ != null) {
        responseBuilder_.dispose();
        responseBuilder_ = null;
      }
      cartId_ = 0;
      if (productsBuilder_ == null) {
        products_ = java.util.Collections.emptyList();
      } else {
        products_ = null;
        productsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cd.proto.CartServiceOuterClass.internal_static_GetCartResponse_descriptor;
    }

    @java.lang.Override
    public com.cd.proto.GetCartResponse getDefaultInstanceForType() {
      return com.cd.proto.GetCartResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.cd.proto.GetCartResponse build() {
      com.cd.proto.GetCartResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cd.proto.GetCartResponse buildPartial() {
      com.cd.proto.GetCartResponse result = new com.cd.proto.GetCartResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.cd.proto.GetCartResponse result) {
      if (productsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          products_ = java.util.Collections.unmodifiableList(products_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.products_ = products_;
      } else {
        result.products_ = productsBuilder_.build();
      }
    }

    private void buildPartial0(com.cd.proto.GetCartResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.response_ = responseBuilder_ == null
            ? response_
            : responseBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.cartId_ = cartId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cd.proto.GetCartResponse) {
        return mergeFrom((com.cd.proto.GetCartResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cd.proto.GetCartResponse other) {
      if (other == com.cd.proto.GetCartResponse.getDefaultInstance()) return this;
      if (other.hasResponse()) {
        mergeResponse(other.getResponse());
      }
      if (other.getCartId() != 0) {
        setCartId(other.getCartId());
      }
      if (productsBuilder_ == null) {
        if (!other.products_.isEmpty()) {
          if (products_.isEmpty()) {
            products_ = other.products_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureProductsIsMutable();
            products_.addAll(other.products_);
          }
          onChanged();
        }
      } else {
        if (!other.products_.isEmpty()) {
          if (productsBuilder_.isEmpty()) {
            productsBuilder_.dispose();
            productsBuilder_ = null;
            products_ = other.products_;
            bitField0_ = (bitField0_ & ~0x00000004);
            productsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getProductsFieldBuilder() : null;
          } else {
            productsBuilder_.addAllMessages(other.products_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              cartId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              com.cd.proto.Product m =
                  input.readMessage(
                      com.cd.proto.Product.parser(),
                      extensionRegistry);
              if (productsBuilder_ == null) {
                ensureProductsIsMutable();
                products_.add(m);
              } else {
                productsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.cd.proto.Response response_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cd.proto.Response, com.cd.proto.Response.Builder, com.cd.proto.ResponseOrBuilder> responseBuilder_;
    /**
     * <code>.Response response = 1;</code>
     * @return Whether the response field is set.
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Response response = 1;</code>
     * @return The response.
     */
    public com.cd.proto.Response getResponse() {
      if (responseBuilder_ == null) {
        return response_ == null ? com.cd.proto.Response.getDefaultInstance() : response_;
      } else {
        return responseBuilder_.getMessage();
      }
    }
    /**
     * <code>.Response response = 1;</code>
     */
    public Builder setResponse(com.cd.proto.Response value) {
      if (responseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
      } else {
        responseBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Response response = 1;</code>
     */
    public Builder setResponse(
        com.cd.proto.Response.Builder builderForValue) {
      if (responseBuilder_ == null) {
        response_ = builderForValue.build();
      } else {
        responseBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Response response = 1;</code>
     */
    public Builder mergeResponse(com.cd.proto.Response value) {
      if (responseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          response_ != null &&
          response_ != com.cd.proto.Response.getDefaultInstance()) {
          getResponseBuilder().mergeFrom(value);
        } else {
          response_ = value;
        }
      } else {
        responseBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Response response = 1;</code>
     */
    public Builder clearResponse() {
      bitField0_ = (bitField0_ & ~0x00000001);
      response_ = null;
      if (responseBuilder_ != null) {
        responseBuilder_.dispose();
        responseBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Response response = 1;</code>
     */
    public com.cd.proto.Response.Builder getResponseBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.Response response = 1;</code>
     */
    public com.cd.proto.ResponseOrBuilder getResponseOrBuilder() {
      if (responseBuilder_ != null) {
        return responseBuilder_.getMessageOrBuilder();
      } else {
        return response_ == null ?
            com.cd.proto.Response.getDefaultInstance() : response_;
      }
    }
    /**
     * <code>.Response response = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cd.proto.Response, com.cd.proto.Response.Builder, com.cd.proto.ResponseOrBuilder> 
        getResponseFieldBuilder() {
      if (responseBuilder_ == null) {
        responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.cd.proto.Response, com.cd.proto.Response.Builder, com.cd.proto.ResponseOrBuilder>(
                getResponse(),
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      return responseBuilder_;
    }

    private int cartId_ ;
    /**
     * <code>int32 cart_id = 2;</code>
     * @return The cartId.
     */
    @java.lang.Override
    public int getCartId() {
      return cartId_;
    }
    /**
     * <code>int32 cart_id = 2;</code>
     * @param value The cartId to set.
     * @return This builder for chaining.
     */
    public Builder setCartId(int value) {

      cartId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 cart_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCartId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      cartId_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.cd.proto.Product> products_ =
      java.util.Collections.emptyList();
    private void ensureProductsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        products_ = new java.util.ArrayList<com.cd.proto.Product>(products_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cd.proto.Product, com.cd.proto.Product.Builder, com.cd.proto.ProductOrBuilder> productsBuilder_;

    /**
     * <code>repeated .Product products = 3;</code>
     */
    public java.util.List<com.cd.proto.Product> getProductsList() {
      if (productsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(products_);
      } else {
        return productsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Product products = 3;</code>
     */
    public int getProductsCount() {
      if (productsBuilder_ == null) {
        return products_.size();
      } else {
        return productsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Product products = 3;</code>
     */
    public com.cd.proto.Product getProducts(int index) {
      if (productsBuilder_ == null) {
        return products_.get(index);
      } else {
        return productsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Product products = 3;</code>
     */
    public Builder setProducts(
        int index, com.cd.proto.Product value) {
      if (productsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductsIsMutable();
        products_.set(index, value);
        onChanged();
      } else {
        productsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Product products = 3;</code>
     */
    public Builder setProducts(
        int index, com.cd.proto.Product.Builder builderForValue) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        products_.set(index, builderForValue.build());
        onChanged();
      } else {
        productsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Product products = 3;</code>
     */
    public Builder addProducts(com.cd.proto.Product value) {
      if (productsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductsIsMutable();
        products_.add(value);
        onChanged();
      } else {
        productsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Product products = 3;</code>
     */
    public Builder addProducts(
        int index, com.cd.proto.Product value) {
      if (productsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductsIsMutable();
        products_.add(index, value);
        onChanged();
      } else {
        productsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Product products = 3;</code>
     */
    public Builder addProducts(
        com.cd.proto.Product.Builder builderForValue) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        products_.add(builderForValue.build());
        onChanged();
      } else {
        productsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Product products = 3;</code>
     */
    public Builder addProducts(
        int index, com.cd.proto.Product.Builder builderForValue) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        products_.add(index, builderForValue.build());
        onChanged();
      } else {
        productsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Product products = 3;</code>
     */
    public Builder addAllProducts(
        java.lang.Iterable<? extends com.cd.proto.Product> values) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, products_);
        onChanged();
      } else {
        productsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Product products = 3;</code>
     */
    public Builder clearProducts() {
      if (productsBuilder_ == null) {
        products_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        productsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Product products = 3;</code>
     */
    public Builder removeProducts(int index) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        products_.remove(index);
        onChanged();
      } else {
        productsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Product products = 3;</code>
     */
    public com.cd.proto.Product.Builder getProductsBuilder(
        int index) {
      return getProductsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Product products = 3;</code>
     */
    public com.cd.proto.ProductOrBuilder getProductsOrBuilder(
        int index) {
      if (productsBuilder_ == null) {
        return products_.get(index);  } else {
        return productsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Product products = 3;</code>
     */
    public java.util.List<? extends com.cd.proto.ProductOrBuilder> 
         getProductsOrBuilderList() {
      if (productsBuilder_ != null) {
        return productsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(products_);
      }
    }
    /**
     * <code>repeated .Product products = 3;</code>
     */
    public com.cd.proto.Product.Builder addProductsBuilder() {
      return getProductsFieldBuilder().addBuilder(
          com.cd.proto.Product.getDefaultInstance());
    }
    /**
     * <code>repeated .Product products = 3;</code>
     */
    public com.cd.proto.Product.Builder addProductsBuilder(
        int index) {
      return getProductsFieldBuilder().addBuilder(
          index, com.cd.proto.Product.getDefaultInstance());
    }
    /**
     * <code>repeated .Product products = 3;</code>
     */
    public java.util.List<com.cd.proto.Product.Builder> 
         getProductsBuilderList() {
      return getProductsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cd.proto.Product, com.cd.proto.Product.Builder, com.cd.proto.ProductOrBuilder> 
        getProductsFieldBuilder() {
      if (productsBuilder_ == null) {
        productsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.cd.proto.Product, com.cd.proto.Product.Builder, com.cd.proto.ProductOrBuilder>(
                products_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        products_ = null;
      }
      return productsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetCartResponse)
  }

  // @@protoc_insertion_point(class_scope:GetCartResponse)
  private static final com.cd.proto.GetCartResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cd.proto.GetCartResponse();
  }

  public static com.cd.proto.GetCartResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetCartResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetCartResponse>() {
    @java.lang.Override
    public GetCartResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetCartResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetCartResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cd.proto.GetCartResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

