// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CartService.proto

package com.cd.proto;

public interface GetCartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetCartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 cart_id = 1;</code>
   * @return The cartId.
   */
  int getCartId();
}
