// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CartService.proto

package com.cd.proto;

public interface GetCartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetCartResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Response response = 1;</code>
   * @return Whether the response field is set.
   */
  boolean hasResponse();
  /**
   * <code>.Response response = 1;</code>
   * @return The response.
   */
  com.cd.proto.Response getResponse();
  /**
   * <code>.Response response = 1;</code>
   */
  com.cd.proto.ResponseOrBuilder getResponseOrBuilder();

  /**
   * <code>int32 cart_id = 2;</code>
   * @return The cartId.
   */
  int getCartId();

  /**
   * <code>repeated .Product products = 3;</code>
   */
  java.util.List<com.cd.proto.Product> 
      getProductsList();
  /**
   * <code>repeated .Product products = 3;</code>
   */
  com.cd.proto.Product getProducts(int index);
  /**
   * <code>repeated .Product products = 3;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .Product products = 3;</code>
   */
  java.util.List<? extends com.cd.proto.ProductOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .Product products = 3;</code>
   */
  com.cd.proto.ProductOrBuilder getProductsOrBuilder(
      int index);
}
