// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CartService.proto

package com.cd.proto;

/**
 * Protobuf type {@code Response}
 */
public final class Response extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Response)
    ResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Response.newBuilder() to construct.
  private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Response() {
    code_ = 0;
    validationErrors_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Response();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cd.proto.CartServiceOuterClass.internal_static_Response_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cd.proto.CartServiceOuterClass.internal_static_Response_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cd.proto.Response.class, com.cd.proto.Response.Builder.class);
  }

  public static final int CODE_FIELD_NUMBER = 1;
  private int code_ = 0;
  /**
   * <code>.ResponseCode code = 1;</code>
   * @return The enum numeric value on the wire for code.
   */
  @java.lang.Override public int getCodeValue() {
    return code_;
  }
  /**
   * <code>.ResponseCode code = 1;</code>
   * @return The code.
   */
  @java.lang.Override public com.cd.proto.ResponseCode getCode() {
    com.cd.proto.ResponseCode result = com.cd.proto.ResponseCode.forNumber(code_);
    return result == null ? com.cd.proto.ResponseCode.UNRECOGNIZED : result;
  }

  public static final int VALIDATION_ERRORS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.cd.proto.ValidationError> validationErrors_;
  /**
   * <code>repeated .ValidationError validation_errors = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.cd.proto.ValidationError> getValidationErrorsList() {
    return validationErrors_;
  }
  /**
   * <code>repeated .ValidationError validation_errors = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.cd.proto.ValidationErrorOrBuilder> 
      getValidationErrorsOrBuilderList() {
    return validationErrors_;
  }
  /**
   * <code>repeated .ValidationError validation_errors = 2;</code>
   */
  @java.lang.Override
  public int getValidationErrorsCount() {
    return validationErrors_.size();
  }
  /**
   * <code>repeated .ValidationError validation_errors = 2;</code>
   */
  @java.lang.Override
  public com.cd.proto.ValidationError getValidationErrors(int index) {
    return validationErrors_.get(index);
  }
  /**
   * <code>repeated .ValidationError validation_errors = 2;</code>
   */
  @java.lang.Override
  public com.cd.proto.ValidationErrorOrBuilder getValidationErrorsOrBuilder(
      int index) {
    return validationErrors_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != com.cd.proto.ResponseCode.OK.getNumber()) {
      output.writeEnum(1, code_);
    }
    for (int i = 0; i < validationErrors_.size(); i++) {
      output.writeMessage(2, validationErrors_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != com.cd.proto.ResponseCode.OK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, code_);
    }
    for (int i = 0; i < validationErrors_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, validationErrors_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cd.proto.Response)) {
      return super.equals(obj);
    }
    com.cd.proto.Response other = (com.cd.proto.Response) obj;

    if (code_ != other.code_) return false;
    if (!getValidationErrorsList()
        .equals(other.getValidationErrorsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + code_;
    if (getValidationErrorsCount() > 0) {
      hash = (37 * hash) + VALIDATION_ERRORS_FIELD_NUMBER;
      hash = (53 * hash) + getValidationErrorsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cd.proto.Response parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cd.proto.Response parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cd.proto.Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cd.proto.Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cd.proto.Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cd.proto.Response parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cd.proto.Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cd.proto.Response parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cd.proto.Response parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cd.proto.Response parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cd.proto.Response parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cd.proto.Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cd.proto.Response prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Response)
      com.cd.proto.ResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cd.proto.CartServiceOuterClass.internal_static_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cd.proto.CartServiceOuterClass.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cd.proto.Response.class, com.cd.proto.Response.Builder.class);
    }

    // Construct using com.cd.proto.Response.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      code_ = 0;
      if (validationErrorsBuilder_ == null) {
        validationErrors_ = java.util.Collections.emptyList();
      } else {
        validationErrors_ = null;
        validationErrorsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cd.proto.CartServiceOuterClass.internal_static_Response_descriptor;
    }

    @java.lang.Override
    public com.cd.proto.Response getDefaultInstanceForType() {
      return com.cd.proto.Response.getDefaultInstance();
    }

    @java.lang.Override
    public com.cd.proto.Response build() {
      com.cd.proto.Response result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cd.proto.Response buildPartial() {
      com.cd.proto.Response result = new com.cd.proto.Response(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.cd.proto.Response result) {
      if (validationErrorsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          validationErrors_ = java.util.Collections.unmodifiableList(validationErrors_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.validationErrors_ = validationErrors_;
      } else {
        result.validationErrors_ = validationErrorsBuilder_.build();
      }
    }

    private void buildPartial0(com.cd.proto.Response result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.code_ = code_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cd.proto.Response) {
        return mergeFrom((com.cd.proto.Response)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cd.proto.Response other) {
      if (other == com.cd.proto.Response.getDefaultInstance()) return this;
      if (other.code_ != 0) {
        setCodeValue(other.getCodeValue());
      }
      if (validationErrorsBuilder_ == null) {
        if (!other.validationErrors_.isEmpty()) {
          if (validationErrors_.isEmpty()) {
            validationErrors_ = other.validationErrors_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureValidationErrorsIsMutable();
            validationErrors_.addAll(other.validationErrors_);
          }
          onChanged();
        }
      } else {
        if (!other.validationErrors_.isEmpty()) {
          if (validationErrorsBuilder_.isEmpty()) {
            validationErrorsBuilder_.dispose();
            validationErrorsBuilder_ = null;
            validationErrors_ = other.validationErrors_;
            bitField0_ = (bitField0_ & ~0x00000002);
            validationErrorsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getValidationErrorsFieldBuilder() : null;
          } else {
            validationErrorsBuilder_.addAllMessages(other.validationErrors_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              code_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              com.cd.proto.ValidationError m =
                  input.readMessage(
                      com.cd.proto.ValidationError.parser(),
                      extensionRegistry);
              if (validationErrorsBuilder_ == null) {
                ensureValidationErrorsIsMutable();
                validationErrors_.add(m);
              } else {
                validationErrorsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int code_ = 0;
    /**
     * <code>.ResponseCode code = 1;</code>
     * @return The enum numeric value on the wire for code.
     */
    @java.lang.Override public int getCodeValue() {
      return code_;
    }
    /**
     * <code>.ResponseCode code = 1;</code>
     * @param value The enum numeric value on the wire for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeValue(int value) {
      code_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ResponseCode code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public com.cd.proto.ResponseCode getCode() {
      com.cd.proto.ResponseCode result = com.cd.proto.ResponseCode.forNumber(code_);
      return result == null ? com.cd.proto.ResponseCode.UNRECOGNIZED : result;
    }
    /**
     * <code>.ResponseCode code = 1;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(com.cd.proto.ResponseCode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      code_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ResponseCode code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      code_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.cd.proto.ValidationError> validationErrors_ =
      java.util.Collections.emptyList();
    private void ensureValidationErrorsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        validationErrors_ = new java.util.ArrayList<com.cd.proto.ValidationError>(validationErrors_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cd.proto.ValidationError, com.cd.proto.ValidationError.Builder, com.cd.proto.ValidationErrorOrBuilder> validationErrorsBuilder_;

    /**
     * <code>repeated .ValidationError validation_errors = 2;</code>
     */
    public java.util.List<com.cd.proto.ValidationError> getValidationErrorsList() {
      if (validationErrorsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(validationErrors_);
      } else {
        return validationErrorsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ValidationError validation_errors = 2;</code>
     */
    public int getValidationErrorsCount() {
      if (validationErrorsBuilder_ == null) {
        return validationErrors_.size();
      } else {
        return validationErrorsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ValidationError validation_errors = 2;</code>
     */
    public com.cd.proto.ValidationError getValidationErrors(int index) {
      if (validationErrorsBuilder_ == null) {
        return validationErrors_.get(index);
      } else {
        return validationErrorsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ValidationError validation_errors = 2;</code>
     */
    public Builder setValidationErrors(
        int index, com.cd.proto.ValidationError value) {
      if (validationErrorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValidationErrorsIsMutable();
        validationErrors_.set(index, value);
        onChanged();
      } else {
        validationErrorsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ValidationError validation_errors = 2;</code>
     */
    public Builder setValidationErrors(
        int index, com.cd.proto.ValidationError.Builder builderForValue) {
      if (validationErrorsBuilder_ == null) {
        ensureValidationErrorsIsMutable();
        validationErrors_.set(index, builderForValue.build());
        onChanged();
      } else {
        validationErrorsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ValidationError validation_errors = 2;</code>
     */
    public Builder addValidationErrors(com.cd.proto.ValidationError value) {
      if (validationErrorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValidationErrorsIsMutable();
        validationErrors_.add(value);
        onChanged();
      } else {
        validationErrorsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ValidationError validation_errors = 2;</code>
     */
    public Builder addValidationErrors(
        int index, com.cd.proto.ValidationError value) {
      if (validationErrorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValidationErrorsIsMutable();
        validationErrors_.add(index, value);
        onChanged();
      } else {
        validationErrorsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ValidationError validation_errors = 2;</code>
     */
    public Builder addValidationErrors(
        com.cd.proto.ValidationError.Builder builderForValue) {
      if (validationErrorsBuilder_ == null) {
        ensureValidationErrorsIsMutable();
        validationErrors_.add(builderForValue.build());
        onChanged();
      } else {
        validationErrorsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ValidationError validation_errors = 2;</code>
     */
    public Builder addValidationErrors(
        int index, com.cd.proto.ValidationError.Builder builderForValue) {
      if (validationErrorsBuilder_ == null) {
        ensureValidationErrorsIsMutable();
        validationErrors_.add(index, builderForValue.build());
        onChanged();
      } else {
        validationErrorsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ValidationError validation_errors = 2;</code>
     */
    public Builder addAllValidationErrors(
        java.lang.Iterable<? extends com.cd.proto.ValidationError> values) {
      if (validationErrorsBuilder_ == null) {
        ensureValidationErrorsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, validationErrors_);
        onChanged();
      } else {
        validationErrorsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ValidationError validation_errors = 2;</code>
     */
    public Builder clearValidationErrors() {
      if (validationErrorsBuilder_ == null) {
        validationErrors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        validationErrorsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ValidationError validation_errors = 2;</code>
     */
    public Builder removeValidationErrors(int index) {
      if (validationErrorsBuilder_ == null) {
        ensureValidationErrorsIsMutable();
        validationErrors_.remove(index);
        onChanged();
      } else {
        validationErrorsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ValidationError validation_errors = 2;</code>
     */
    public com.cd.proto.ValidationError.Builder getValidationErrorsBuilder(
        int index) {
      return getValidationErrorsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ValidationError validation_errors = 2;</code>
     */
    public com.cd.proto.ValidationErrorOrBuilder getValidationErrorsOrBuilder(
        int index) {
      if (validationErrorsBuilder_ == null) {
        return validationErrors_.get(index);  } else {
        return validationErrorsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ValidationError validation_errors = 2;</code>
     */
    public java.util.List<? extends com.cd.proto.ValidationErrorOrBuilder> 
         getValidationErrorsOrBuilderList() {
      if (validationErrorsBuilder_ != null) {
        return validationErrorsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(validationErrors_);
      }
    }
    /**
     * <code>repeated .ValidationError validation_errors = 2;</code>
     */
    public com.cd.proto.ValidationError.Builder addValidationErrorsBuilder() {
      return getValidationErrorsFieldBuilder().addBuilder(
          com.cd.proto.ValidationError.getDefaultInstance());
    }
    /**
     * <code>repeated .ValidationError validation_errors = 2;</code>
     */
    public com.cd.proto.ValidationError.Builder addValidationErrorsBuilder(
        int index) {
      return getValidationErrorsFieldBuilder().addBuilder(
          index, com.cd.proto.ValidationError.getDefaultInstance());
    }
    /**
     * <code>repeated .ValidationError validation_errors = 2;</code>
     */
    public java.util.List<com.cd.proto.ValidationError.Builder> 
         getValidationErrorsBuilderList() {
      return getValidationErrorsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cd.proto.ValidationError, com.cd.proto.ValidationError.Builder, com.cd.proto.ValidationErrorOrBuilder> 
        getValidationErrorsFieldBuilder() {
      if (validationErrorsBuilder_ == null) {
        validationErrorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.cd.proto.ValidationError, com.cd.proto.ValidationError.Builder, com.cd.proto.ValidationErrorOrBuilder>(
                validationErrors_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        validationErrors_ = null;
      }
      return validationErrorsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Response)
  }

  // @@protoc_insertion_point(class_scope:Response)
  private static final com.cd.proto.Response DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cd.proto.Response();
  }

  public static com.cd.proto.Response getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Response>
      PARSER = new com.google.protobuf.AbstractParser<Response>() {
    @java.lang.Override
    public Response parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Response> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Response> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cd.proto.Response getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

