// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CartService.proto

package com.cd.proto;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ResponseCode code = 1;</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <code>.ResponseCode code = 1;</code>
   * @return The code.
   */
  com.cd.proto.ResponseCode getCode();

  /**
   * <code>repeated .ValidationError validation_errors = 2;</code>
   */
  java.util.List<com.cd.proto.ValidationError> 
      getValidationErrorsList();
  /**
   * <code>repeated .ValidationError validation_errors = 2;</code>
   */
  com.cd.proto.ValidationError getValidationErrors(int index);
  /**
   * <code>repeated .ValidationError validation_errors = 2;</code>
   */
  int getValidationErrorsCount();
  /**
   * <code>repeated .ValidationError validation_errors = 2;</code>
   */
  java.util.List<? extends com.cd.proto.ValidationErrorOrBuilder> 
      getValidationErrorsOrBuilderList();
  /**
   * <code>repeated .ValidationError validation_errors = 2;</code>
   */
  com.cd.proto.ValidationErrorOrBuilder getValidationErrorsOrBuilder(
      int index);
}
