// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CartService.proto

package com.cd.proto;

public interface ValidationErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ValidationError)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string field = 1;</code>
   * @return The field.
   */
  java.lang.String getField();
  /**
   * <code>string field = 1;</code>
   * @return The bytes for field.
   */
  com.google.protobuf.ByteString
      getFieldBytes();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
